# Generated by Django 4.1.2 on 2022-10-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('celebs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.celeb')),
            ],
        ),
    ]
