# Generated by Django 4.1.2 on 2022-10-09 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_blinditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='celebs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='main_app.celeb'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date_taken', models.DateField(default=datetime.date.today)),
                ('celebs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='main_app.celeb')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('celebs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_board', to='main_app.celeb')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=500)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('celebs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='main_app.celeb')),
            ],
        ),
    ]
