# Generated by Django 4.1.2 on 2022-10-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_photo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
