# Generated by Django 4.1.2 on 2022-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_article_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='celebs',
        ),
        migrations.AddField(
            model_name='photo',
            name='celebs',
            field=models.ManyToManyField(to='main_app.celeb'),
        ),
    ]
