# Generated by Django 4.1.2 on 2022-10-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_photocomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomments',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.photo'),
        ),
    ]
