# Generated by Django 4.1.2 on 2022-10-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_photocomments_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomments',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
