# Generated by Django 4.1.2 on 2022-10-11 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_photocomments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBoardComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('messageboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.messageboard')),
            ],
        ),
        migrations.CreateModel(
            name='BlindItemComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('blind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.blinditem')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.article')),
            ],
        ),
    ]
