# Generated by Django 4.1.2 on 2022-10-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_videocomments_messageboardcomments_blinditemcomments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComments',
            new_name='ArticleComment',
        ),
        migrations.RenameModel(
            old_name='BlindItemComments',
            new_name='BlindItemComment',
        ),
        migrations.RenameModel(
            old_name='MessageBoardComments',
            new_name='MessageBoardComment',
        ),
        migrations.RenameModel(
            old_name='VideoComments',
            new_name='VideoComment',
        ),
    ]
