# Generated by Django 4.1.2 on 2022-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_rename_articlecomments_articlecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='coverphoto',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
