# Generated by Django 4.1.2 on 2022-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_celeb_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='articlesphoto',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='celeb',
            name='blinditemsphoto',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='celeb',
            name='messageboardsphoto',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='celeb',
            name='photosphoto',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='celeb',
            name='videosphoto',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
